---
- name: Disable ISIS Protocol on Juniper Router
  hosts: all
  gather_facts: no
  connection: local
  tasks:
    - name: Disable ISIS Protocol
      junos_command:
        commands:
          - set protocols isis disable
      register: result

    - name: Commit Changes
      junos_command:
        commands:
          - commit and-quit
      when: "result.stdout.find('commit complete') != -1"