---
- name: Check Installed Packages
  hosts: all   # Replace with the name of your server group or individual server
  become: yes                # Run tasks with administrative privileges (sudo)

  tasks:
    - name: List installed packages
      command: sudo apt list –-installed | less
      register: installed_packages

    - name: Display installed packages
      debug:
        var: installed_packages.stdout_lines
